spring :
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dev_neo
    username: root
    password: Pavan@16

  jpa:
    database-platform: org.hibernate.dialect.MySQL8InnoDBBialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  sql:
    init:
      mode: never